from cnnClassifier.components.data_ingestion import DataIngestion
from cnnClassifier.components.prepare_base_model import PrepareBaseModel
from cnnClassifier.components.model_trainer import ModelTrainer
from cnnClassifier.components.model_evaluation_mlflow import ModelEvaluation